### ISSUE TITLE
Doesn't work with latest torch 1.5.0 update 

### ISSUE THREAD

**Issue by alexanderimanicowenrivers** [tristandeleu/pytorch-meta#49]
Traceback (most recent call last):
  File "/home/alexc/code/cadam/MAML/main_miniimagenet.py", line 480, in <module>
    from torchmeta.utils.data import BatchMetaDataLoader
  File "/home/alexc/anaconda3/envs/cadam_new/lib/python3.7/site-packages/torchmeta/__init__.py", line 1, in <module>
    from torchmeta import datasets
  File "/home/alexc/anaconda3/envs/cadam_new/lib/python3.7/site-packages/torchmeta/datasets/__init__.py", line 1, in <module>
    from torchmeta.datasets.triplemnist import TripleMNIST
  File "/home/alexc/anaconda3/envs/cadam_new/lib/python3.7/site-packages/torchmeta/datasets/triplemnist.py", line 11, in <module>
    from torchmeta.datasets.utils import get_asset
  File "/home/alexc/anaconda3/envs/cadam_new/lib/python3.7/site-packages/torchmeta/datasets/utils.py", line 3, in <module>
    from torchvision.datasets.utils import makedir_exist_ok, check_integrity
ImportError: cannot import name 'makedir_exist_ok' from 'torchvision.datasets.utils' (/home/alexc/anaconda3/envs/cadam_new/lib/python3.7/site-packages/torchvision/datasets/utils.py)

Can you patch these up please and commit :)

**Comment by tristandeleu** [comment]
What is your version of Torchmeta and Torchvision? This issue should have been fixed in Torchmeta v1.4.2 (latest being 1.4.3)

**Comment by alexanderimanicowenrivers** [comment]
Ahh I didn’t realise there was a nice release. This would of fixed it for sure. Thanks!!
